version:  '3.7'
services:
  db:
    image: postgres:12
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: root