version:  '3.7'
services:
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB : mydb
      POSTGRES_USER : postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080